# Generated by Django 4.2.4 on 2023-08-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Details', '0002_customuser_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(max_length=100),
        ),
    ]
