# Generated by Django 4.2.4 on 2023-08-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Details', '0003_alter_customuser_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
            ],
        ),
    ]
