version: "3.9"
   
services:
  # db:
  #   image: postgres
  #   volumes:
  #     - ./data/db:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_HOST=db
  web:
    build:
     dockerfile: Dockerfile.dev
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/API_CRUD
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=dme.settings.docker_local
    depends_on:
      - db
  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=postgres
  #   ports:
  #     - "5050:80"

